[2022-10-15 21:42:49,371] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: extract_data_from_ftp_to_s3.ftp_to_s3_task scheduled__2022-10-15T20:00:00+00:00 [queued]>
[2022-10-15 21:42:49,391] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: extract_data_from_ftp_to_s3.ftp_to_s3_task scheduled__2022-10-15T20:00:00+00:00 [queued]>
[2022-10-15 21:42:49,391] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-10-15 21:42:49,391] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2022-10-15 21:42:49,392] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-10-15 21:42:49,423] {taskinstance.py:1397} INFO - Executing <Task(SFTPToS3Operator): ftp_to_s3_task> on 2022-10-15 20:00:00+00:00
[2022-10-15 21:42:49,435] {standard_task_runner.py:52} INFO - Started process 11885 to run task
[2022-10-15 21:42:49,439] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'extract_data_from_ftp_to_s3', 'ftp_to_s3_task', 'scheduled__2022-10-15T20:00:00+00:00', '--job-id', '66', '--raw', '--subdir', 'DAGS_FOLDER/extract_data_from_ftp_to_s3.py', '--cfg-path', '/tmp/tmpdga5hg_0', '--error-file', '/tmp/tmpy8ypo9n2']
[2022-10-15 21:42:49,440] {standard_task_runner.py:80} INFO - Job 66: Subtask ftp_to_s3_task
[2022-10-15 21:42:49,563] {task_command.py:371} INFO - Running <TaskInstance: extract_data_from_ftp_to_s3.ftp_to_s3_task scheduled__2022-10-15T20:00:00+00:00 [running]> on host e1202d78ead4
[2022-10-15 21:42:49,700] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=extract_data_from_ftp_to_s3
AIRFLOW_CTX_TASK_ID=ftp_to_s3_task
AIRFLOW_CTX_EXECUTION_DATE=2022-10-15T20:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-10-15T20:00:00+00:00
[2022-10-15 21:42:49,742] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/transfers/sftp_to_s3.py", line 82, in execute
    ssh_hook = SSHHook(ssh_conn_id=self.sftp_conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/ssh/hooks/ssh.py", line 147, in __init__
    conn = self.get_connection(self.ssh_conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/base.py", line 67, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/connection.py", line 430, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `ssh_default` isn't defined
[2022-10-15 21:42:49,749] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=extract_data_from_ftp_to_s3, task_id=ftp_to_s3_task, execution_date=20221015T200000, start_date=20221015T214249, end_date=20221015T214249
[2022-10-15 21:42:49,772] {standard_task_runner.py:97} ERROR - Failed to execute job 66 for task ftp_to_s3_task (The conn_id `ssh_default` isn't defined; 11885)
[2022-10-15 21:42:49,810] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-10-15 21:42:49,910] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-10-15 21:42:49,952] {dagrun.py:549} ERROR - Marking run <DagRun extract_data_from_ftp_to_s3 @ 2022-10-15 20:00:00+00:00: scheduled__2022-10-15T20:00:00+00:00, externally triggered: False> failed
[2022-10-15 21:42:49,953] {dagrun.py:624} INFO - DagRun Finished: dag_id=extract_data_from_ftp_to_s3, execution_date=2022-10-15 20:00:00+00:00, run_id=scheduled__2022-10-15T20:00:00+00:00, run_start_date=2022-10-15 21:42:48.454722+00:00, run_end_date=2022-10-15 21:42:49.953459+00:00, run_duration=1.498737, state=failed, external_trigger=False, run_type=scheduled, data_interval_start=2022-10-15 20:00:00+00:00, data_interval_end=2022-10-15 21:00:00+00:00, dag_hash=b245321ed04acad5cfe4c7bda42f881f
